language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: 'Lint check'
      name: 'Lint check'
      script: npm run eslint
    - stage: 'Run typescript build'
      name: 'Run typescript build'
      script: npm run build
